### ISSUE TITLE
Написать бизнес логику перехода по короткой ссылке

### ISSUE THREAD

**Issue by AlexAntufiev** [NoXml/Shortly#7]
Длина короткой ссылки должна быть 6 символов.
Алфавит цифры и английские буквы(регистр не учитывается).
Сначала нужно придумать и написать идею, по которой будет генерироваться короткая ссылка относительное длинной

**Comment by shpikich** [comment]
@AlexAntufiev Можно использовать генератор последовательности случайных цифр и английских букв длиной в 6 символов

**Comment by AlexAntufiev** [comment]
Но тогда мы неравномерно распределим количество наших ссылок, но давай начнём с простого)
